services:
  futurecoder:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        ALL_PROXY: ${ALL_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
        all_proxy: ${all_proxy:-}
        no_proxy: ${no_proxy:-}
        FUTURECODER_LANGUAGE: ${FUTURECODER_LANGUAGE:-zh}
        FUTURECODER_LANGUAGES: ${FUTURECODER_LANGUAGES:-zh}
        REACT_APP_LANGUAGE: ${REACT_APP_LANGUAGE:-zh}
        ALLOW_INCOMPLETE_TRANSLATIONS: ${ALLOW_INCOMPLETE_TRANSLATIONS:-1}
    container_name: futurecoder
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      ALL_PROXY: ${ALL_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
      http_proxy: ${http_proxy:-}
      https_proxy: ${https_proxy:-}
      all_proxy: ${all_proxy:-}
      no_proxy: ${no_proxy:-}
      FUTURECODER_LANGUAGE: ${FUTURECODER_LANGUAGE:-zh}
      FUTURECODER_LANGUAGES: ${FUTURECODER_LANGUAGES:-zh}
      REACT_APP_LANGUAGE: ${REACT_APP_LANGUAGE:-zh}
      ALLOW_INCOMPLETE_TRANSLATIONS: ${ALLOW_INCOMPLETE_TRANSLATIONS:-1}
    volumes:
      - ..:/app
      - /app/frontend/node_modules
    working_dir: /app/frontend
